import Head from "next/head";
import Image from "next/image";
import { FaSearch, FaPizzaSlice } from "react-icons/fa";
import { ImPacman } from "react-icons/im";
import { Navitems } from "../src/data/data";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* NAV Start */}
      <nav className='flex flex-col w-[150px] fixed h-screen py-10 justify-between'>
        <div className='flex justify-center'>
          {/* icono 1 */}
          <div className='p-2 text-[#132251] bg-[#fef8f2] w-[62px] h-[62px] text-2xl flex flex-col gap-1 justify-center items-center'>
            <ImPacman></ImPacman>
            <div className='h-[2px] w-3/4 bg-[#ec7905]'></div>
          </div>
        </div>
        {/* iconos app 8 */}
        <div className='flex flex-col gap-8 justify-center items-center text-gray-500 '>
          {Navitems.map(({ name, Icon, idx }) => (
            <div key={name + idx} className='text-2xl flex flex-col items-center '>
              <Icon></Icon>
              <span className='text-sm'>{name}</span>
            </div>
          ))}
        </div>
        {/* profile Avatar */}
        <div className='flex items-center flex-col'>
          <Image src='/avatar1.png' width='46' height='46' alt='Jaguar ek caricatura' className='rounded-full'></Image>
          <span>Profile</span>
        </div>
      </nav>
      {/* NAV end */}
      {/* Content */}
      <div className='grid grid-cols-8 pl-[150px] w-full h-screen '>
        <main className='col-span-6'>
          {/* top part design  */}
          <div className='flex justify-between w-3/4 py-10 items-center'>
            <div className='bg-white py-2 pr-3 rounded-lg flex justify-between items-center w-2/4'>
              <input placeholder='Search category or menu' type='text' className=' ml-4 w-[90%] focus:outline-slate-100' />
              <FaSearch className='text-gray-500'></FaSearch>
            </div>
            <div>
              <b className='text-[#ec7905] pr-8 '> 5 items out of stock</b>
            </div>
          </div>
          {/* Top part end */}
          {/* Chips  */}
          <div className='flex justify-between items-center w-[65%]'>
            <div className='bg-[#fef0e1] flex items-center justify-around px-4 py-1 rounded-full text-[#ec7905] '>
              <Image src='/pizza.png' width='32' height='32' alt='pizza'></Image>
              <span className='text-[#ec7905] font-bold ml-2'>Pizza</span>
            </div>
            <div className='bg-[#ebebeb] flex items-center justify-around px-4 py-1 rounded-full  text-[#9a9a9a]'>
              <Image src='/burger.png' width='32' height='32' alt='pizza'></Image>
              <span className='font-medium ml-2'>Burger</span>
            </div>
            <div className='bg-[#ebebeb] flex items-center justify-around px-4 py-1 rounded-full  text-[#9a9a9a]'>
              <Image src='/rise.png' width='32' height='32' alt='pizza'></Image>
              <span className='font-medium ml-2'>Rice</span>
            </div>
            <div className='bg-[#ebebeb] flex items-center justify-around px-4 py-1 rounded-full  text-[#9a9a9a]'>
              <Image src='/icecream.png' width='32' height='32' alt='pizza'></Image>
              <span className='font-medium ml-2'>Snacks</span>
            </div>
            <div className='bg-[#ebebeb] flex items-center justify-around px-4 py-1 rounded-full  text-[#9a9a9a]'>
              <Image src='/milk.png' width='32' height='32' alt='pizza'></Image>
              <span className='font-medium ml-2'>Drinks</span>
            </div>
          </div>
        </main>

        {/* Shoping Cart */}
        <aside className='bg-blue-800 col-span-2'></aside>
      </div>
    </div>
  );
}
