import Head from "next/head";
import { useState } from "react";
import { FaGithubSquare, FaGratipay, FaAlignRight, FaTimes } from "react-icons/fa";
import Chips from "../src/components/Chips";
import Search from "../src/components/Search";
import SideBar from "../src/components/SideBar";

export default function Home() {
  const [showMenu, setShowMenu] = useState(false);

  const toogleMenu = () => {
    setShowMenu(!showMenu);
  };
  return (
    <div className='min-h-screen w-full'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* NAV Start */}
      <SideBar showMenu={showMenu}></SideBar>
      {/* Mobile Menu */}
      <nav className='bg-[#ec7905] flex items-center justify-around lg:hidden w-full text-white fixed bottom-0 left-0 py-2 px-8 text-4xl rounded-t-2xl'>
        <button className='p-1'>
          <FaGithubSquare></FaGithubSquare>
        </button>{" "}
        <button>
          <FaGratipay className='p-1'></FaGratipay>
        </button>
        <button onClick={toogleMenu}>{showMenu ? <FaTimes></FaTimes> : <FaAlignRight className='p-1'></FaAlignRight>}</button>
        {/* menu | close */}
      </nav>
      {/* Mobile Menu END*/}

      {/* NAV end */}
      {/* Content */}
      <div className='grid grid-cols-8 px-6 md:pl-[150px] w-full  '>
        <main className='col-span-full lg:col-span-6'>
          {/* top part design  */}
          <Search></Search>

          {/* Top part end */}
          {/* Chips  */}
          <Chips></Chips>
        </main>

        {/* Shoping Cart */}
        <aside className='bg-blue-800 hidden lg:block col-span-2'></aside>
      </div>
    </div>
  );
}
